CREATE TABLE [dbo].[TBDISCIPLINA_TBMATERIA] (
    [DISCIPLINA_ID] INT NOT NULL,
    [MATERIA_ID]    INT NOT NULL,
    CONSTRAINT [FK_TBDISCIPLINA_TBMATERIATBDISCIPLINA] FOREIGN KEY ([DISCIPLINA_ID]) REFERENCES [dbo].[TBDISCIPLINA] ([ID]),
    CONSTRAINT [FK_TBDISCIPLINA_TBMATERIATBMATERIA] FOREIGN KEY ([MATERIA_ID]) REFERENCES [dbo].[TBMATERIA] ([ID])
);

