CREATE TABLE [dbo].[TBQUESTAO] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [MATERIA_ID]         INT           NOT NULL,
    [ENUNCIADO]          VARCHAR (MAX) NOT NULL,
    [ALTERNATIVACORRETA] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TBQUESTAO] PRIMARY KEY CLUSTERED ([ID] ASC)
);



