CREATE TABLE [dbo].[TBTESTE_TBQUESTAO] (
    [TESTE_ID]   INT NOT NULL,
    [QUESTAO_ID] INT NOT NULL,
    CONSTRAINT [FK_TBTESTE_TBQUESTAOTBQUESTAO] FOREIGN KEY ([QUESTAO_ID]) REFERENCES [dbo].[TBQUESTAO] ([ID]),
    CONSTRAINT [FK_TBTESTE_TBQUESTAOTBTESTE] FOREIGN KEY ([TESTE_ID]) REFERENCES [dbo].[TBTESTE] ([ID])
);

